### create new author
POST http://localhost:9000/api/authors
Content-Type: application/json

{
  "First":"hema",
  "Last":"Elmourchidi"
}


### get all books
GET http://localhost:9000/api/books

### get single book
GET http://localhost:9000/api/books/1

### Create new book 
POST http://localhost:9000/api/books
Content-Type: application/json

{
  "Isbn":"123",
  "Title":"book1",
  "Price": 123,
  "AuthorID": 1
}

### delete a book by id
DELETE http://localhost:9000/api/books/1


### update book

PUT http://localhost:9000/api/books/3
Content-Type: application/json

{
  "Isbn":"123456",
  "Title": "book updated",
  "Price": 556,
  "AuthorID": 2
}


### get all authors
GET http://localhost:9000/api/authors/


